version: "3.7"
services:
  traefik:
    image: traefik:v2.1.2
    networks:
      - network-delivery
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      TRAEFIK_ACCESSLOG: "true"
      TRAEFIK_LOG_LEVEL: info
      TRAEFIK_API_DASHBOARD: "true"
      TRAEFIK_API_INSECURE: "true"
      TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS: ":80"
      TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS: ":443"
      TRAEFIK_SERVERSTRANSPORT_INSECURESKIPVERIFY: "true"
      TRAEFIK_PROVIDERS_DOCKER: "true"
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: "false"
      TRAEFIK_PROVIDERS_DOCKER_ENDPOINT: unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # -------------------------------------------------------------------------- #
  delivery:
    image: delivery:latest
    build:
      context: ../delivery
    networks:
      network-delivery:
        aliases:
          - delivery.lan.com
    restart: always
    environment:
      TEMPLATES_DIR: /delivery/templates
    labels:
      traefik.enable: "true"
      traefik.docker.network: network-delivery
      traefik.http.routers.delivery.entrypoints: http
      traefik.http.routers.delivery.rule: Host(`delivery.lan.com`)
      traefik.http.services.delivery.loadbalancer.server.port: 8080
      traefik.http.services.delivery.loadbalancer.sticky: "true"

  # -------------------------------------------------------------------------- #
  gitlab:
    image: gitlab/gitlab-ce:latest
    networks:
      network-delivery:
        aliases:
          - gitlab.lan.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.lan.com'
        nginx['listen_port'] = 80
        gitlab_rails['initial_root_password'] = "delivery"
    volumes:
      - ./gitlab/data:/var/opt/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/config:/etc/gitlab
    labels:
      traefik.enable: "true"
      traefik.docker.network: network-delivery
      traefik.http.routers.gitlab.entrypoints: http
      traefik.http.routers.gitlab.rule: Host(`gitlab.lan.com`)
      traefik.http.services.gitlab.loadbalancer.server.port: 80

# -------------------------------- networks ---------------------------------- #
networks:
  network-delivery:
    driver: bridge
